import Hero from "@/components/about/hero";
import Mission from "@/components/about/mission";
import Team from "@/components/about/team";
import OurValues from "@/components/about/values";
import Waitlist from "@/components/about/waitlist";
import DefaultLayout from "@/components/layouts/DefaultLayout";
import NavBar from "@/components/layouts/NavBar";
import Head from "next/head";
import Image from "next/image";

const About = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="flex flex-col">
        <Hero />
        <Mission />
        <OurValues />
        <Team />
        <Waitlist />
      </main>
    </>
  );
};

About.getLayout = (page: any) => <DefaultLayout>{page}</DefaultLayout>;

export default About;
